import React,{useState,useEffect} from 'react'
import {FormFiled,Card,Loader} from '../components'
import {useLocation} from 'react-router-dom'
const RenderCard=({data,title})=>{
    if(data.length > 0){
        return data.map((post,index)=>(
            <div key={index} className='col-12 col-sm-6 col-md-4 col-lg-3'>
                <Card {...post}/>
            </div>
        ))
    }

    return (
    <h2 key={1} style={{color:'#6449ff',fontWeight:'bold'}} className='text-uppercase'>{title}</h2>
    )
}

const Home = () => {
    const location=useLocation();
    const [loading,setLoading] =useState(false);
    const [allPosts,setAllPosts]=useState([]);
    const [searchText,setSearchText]=useState('');
    const [searchResult,setSearchResult]=useState(null);
    const [searchTimeOut,setSearchTimeOut]=useState(null);
    useEffect(()=>{
        const fetchPosts = async ()=>{
            try {
                setLoading(true);
                const res=await fetch('http://localhost:8080/api/v1/post',{
                    method:'GET',
                    headers:{'Content-Type':'application/json'}
                });
                if(res.ok){
                    const result=await res.json();
                    setAllPosts(result?.data.reverse());
                }
            } catch (error) {
                console.log(error);
            }finally{
                setLoading(false);
            }
        }
        fetchPosts();
    },[]);
    const handleSearch=(e)=>{
        clearTimeout(searchTimeOut);
        setSearchText(e.target.value);
        setSearchTimeOut(
        setTimeout(()=>{
            const searchResult=allPosts.filter((item)=>item?.name.toLowerCase().includes(searchText.toLowerCase()) || item?.prompt.toLowerCase().includes(searchText.toLowerCase()));
            setSearchResult(searchResult);
        },500));
    }
  return (
    <section className='mx-auto' style={{maxWidth:'80rem'}}>
        <div>
            <h1 style={{fontWeight:'bold',color:'#222328',fontSize:'32px'}}>The Community Showcase</h1>
            <p style={{maxWidth:'700px',color:'#666e75',fontSize:'16px'}} className='mt-2'>Browse through a collection of 
            imaginative and visually stunning generated by DALL-E AI
            </p>
        </div>
        <div className='mt-5'>
            <FormFiled 
            labelName="Search Post"
            type='text'
            name='text'
            placeholder='Search Posts'
            value={searchText}
            handleChange={handleSearch}
            />
        </div>
        <div className='mt-3'>
            {loading ? (
                <div className='d-flex justify-content-center align-items-center'>
                    <Loader />
                </div>
            ) : (
                <>
                {
                    searchText && (
                        <h2 style={{color:'#666e75',font:'medium'}} className='mb-3'>Show Result For <span style={{color:'#222328'}}>{searchText}</span></h2>
                    )
                }
                <div className='row g-3'>
                    {
                        searchText ? (
                            <RenderCard 
                            data={searchResult}
                            title='No Search Result Founded'
                            />
                        ):(
                            <RenderCard 
                            data={allPosts}
                            title='No Posts Found'
                            />
                        )
                    }
                </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home